version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/node:16.17-alpine3.15
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            npm install --save
      - run:
          name: Run Unit tests
          command: |
            npx mocha tests/ --reporter mochawesome --reporter-options reportDir=tets-results,reportFileName=tets-results
      - store_test_results:
          path: tets-results
      - store_artifacts:
          path: tets-results

workflows:
  build_tests:
    jobs:
      - run_tests