version: 2.1
orbs:
  heroku: circleci/heroku@2.0.0

workflows:
  test-build-release:
    jobs:
      - tests
      - build:
          requires:
            - tests
      - release:
          requires:
            - build
          type: approval

jobs:
  tests:
    docker:
      - image: cimg/node:18.10.0
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
      - run:
          name: Install npm dependencies
          command: |
            npm install
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths: 
            - node_modules 
      # - run:
      #     name: Run Unit tests
      #     command: |
      #       npx mocha tests/ --reporter mochawesome --reporter-options reportDir=tets-results,reportFileName=tets-results
      # - store_test_results:
      #     path: tets-results
      # - store_artifacts:
      #     path: tets-results

  build:
    docker:
      - image: cimg/node:18.10.0
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    environment:
      PORT: 80
    steps:
      - checkout
      - heroku/install
      - heroku/check-authentication
      - setup_remote_docker:
          version: 20.10.14
      - heroku/push-docker-image:
          app-name: local-demo-app
          process-types: web

  release:
    docker:
      - image: cimg/node:18.10.0
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - heroku/install
      - setup_remote_docker:
          version: 20.10.14
      - heroku/release-docker-image:
          app-name: local-demo-app
          process-types: web